CREATE TABLESPACE TS_SOTEC_PDV DATAFILE 'C:\oraclexe\app\oracle\oradata\XE\TS_SOTEC_PDV.dbf' SIZE 100M
    EXTENT MANAGEMENT LOCAL 
    SEGMENT SPACE MANAGEMENT AUTO;

CREATE TEMPORARY TABLESPACE TS_TEMP_SOTEC_PDV
  TEMPFILE 'C:\oraclexe\app\oracle\oradata\XE\TS_TEMP_SOTEC_PDV.dbf' SIZE 50M REUSE
  EXTENT MANAGEMENT LOCAL UNIFORM SIZE 10M;
